services:
  client:
    build: ./client
    ports:
      - "8080:80"
    depends_on:
      - server
    restart: always

  server:
    build: ./server
    ports:
      - "8081:8080"
    environment:
      - NODE_ENV=production
    restart: always
